# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: tomling
google_analytics: UA-110338942-1
title: Tom Ling

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Posts

description: Tom Ling's Personal Blog
author:
  name: Tom Ling
  #email: tomjling@gmail.com
  #github: dbtek
  twitter: _TomLing
 #pinterest: asd123
  linkedin: tom-ling-b5315280
  bio: Software Engineer at the United Kingdom Hydrographic Office This blog will mainly focus on serverless, Azure, C# and secure development in a .NET world.
  email_md5: d50df30c69adf3de8cb582186495f6cc

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
